// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT-z6AFxkOAeP4NU08y0HFoHhEZEP4MDM',
    appId: '1:854914086833:web:178a4572600fc26a8a2f90',
    messagingSenderId: '854914086833',
    projectId: 'smart-insulin-app',
    authDomain: 'smart-insulin-app.firebaseapp.com',
    storageBucket: 'smart-insulin-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChT6iKgsJLie1EbTHKb89SDkYRmojIO5o',
    appId: '1:854914086833:android:af440ae5fdefb7ab8a2f90',
    messagingSenderId: '854914086833',
    projectId: 'smart-insulin-app',
    storageBucket: 'smart-insulin-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBKn7oO41vulNQsEcu5XNnkxAkA1ezWzk',
    appId: '1:854914086833:ios:4e09de54edb2c8dc8a2f90',
    messagingSenderId: '854914086833',
    projectId: 'smart-insulin-app',
    storageBucket: 'smart-insulin-app.firebasestorage.app',
    iosBundleId: 'com.example.smartInsulinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBKn7oO41vulNQsEcu5XNnkxAkA1ezWzk',
    appId: '1:854914086833:ios:4e09de54edb2c8dc8a2f90',
    messagingSenderId: '854914086833',
    projectId: 'smart-insulin-app',
    storageBucket: 'smart-insulin-app.firebasestorage.app',
    iosBundleId: 'com.example.smartInsulinApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT-z6AFxkOAeP4NU08y0HFoHhEZEP4MDM',
    appId: '1:854914086833:web:8817a3051fa76c8f8a2f90',
    messagingSenderId: '854914086833',
    projectId: 'smart-insulin-app',
    authDomain: 'smart-insulin-app.firebaseapp.com',
    storageBucket: 'smart-insulin-app.firebasestorage.app',
  );
}
